# Example UI definition for whip_ui
# This demonstrates the new hierarchical TOML widget definition format

# Window configuration
[window]
size = [800.0, 600.0]
background_color = { Hex = "#2D3748" }

# Root widget node defining the UI hierarchy
[root]
id = "main_container"
widget_type = { type = "Container", direction = "Column" }
layout = { size = [800.0, 600.0], position = [0.0, 0.0, 0.0] }
style = { background_color = { Hex = "#2D3748" } }
behavior = { visible = true, interactive = false }

# Header
[[root.children]]
id = "header"
widget_type = { type = "Container", direction = "Row" }
layout = { size = [800.0, 80.0], padding = { top = 10.0, right = 20.0, bottom = 10.0, left = 20.0 } }
style = { background_color = { Hex = "#1A202C" }, border_width = 1.0, border_color = { Hex = "#4A5568" } }
behavior = { visible = true }

# Header title
[[root.children.children]]
id = "title"
widget_type = { type = "Text", content = "whip_ui Example", editable = false }
layout = { flex_grow = 1.0 }
style = { text_color = { Named = "white" }, text_size = 24.0 }
behavior = { visible = true }

# Header navigation buttons container
[[root.children.children]]
id = "nav_buttons"
widget_type = { type = "Container", direction = "Row" }
layout = { size = [200.0, 60.0] }
behavior = { visible = true }

# Content area
[[root.children]]
id = "content_area"
widget_type = { type = "Container", direction = "Row" }
layout = { size = [800.0, 440.0], padding = { top = 20.0, right = 20.0, bottom = 20.0, left = 20.0 } }
style = { background_color = { Rgba = { r = 255, g = 255, b = 255, a = 0.05 } } }
behavior = { visible = true }

# Footer
[[root.children]]
id = "footer"
widget_type = { type = "Container", direction = "Row" }
layout = { size = [800.0, 60.0], padding = { top = 15.0, right = 20.0, bottom = 15.0, left = 20.0 } }
style = { 
    background_color = { Hex = "#1A202C" },
    border_width = 1.0,
    border_color = { Hex = "#4A5568" }
}
behavior = { visible = true }