[package]
name = "rusty_whip"
version = "0.1.0"
edition = "2021"
build = "build.rs" 

[lib]
name = "rusty_whip"

[dependencies]
ash = "0.38"
vk-mem = "0.4"
raw-window-handle = "0.6"
winit = "0.30.9"
ash-window = "0.13"
glam = "0.30"